index_col: 'id'
target_col: 'price'

test_size: 0.2
random_state: 42

model_params:
  n_estimators: 100
  max_depth: 10
  random_state: 42
  n_jobs: -1

cv_params:
  n_splits: 5
  n_jobs: -1
  metrics:
    - neg_mean_squared_error
    - neg_mean_absolute_error
    - r2

